2. If B is rotated 90 degrees about the first axis relative to N, and R is rotated -90 degrees about the second axis relative to N, what is the [BR] DCM?

In [ ]:
import numpy as np

# Standard Rotation Matrix for first axis rotation
def R1(theta):
    c, s = np.cos(theta), np.sin(theta)
    return np.array([
        [1, 0, 0],
        [0, c, s],
        [0, -s, c]
    ])
# Standard Rotation Matrix for first axis rotation
def R2(theta):
    c, s = np.cos(theta), np.sin(theta)
    return np.array([
        [c, 0, -s],
        [0, 1, 0],
        [s, 0, c]
    ])

# Convert degrees to radians
deg = np.pi / 180

# Given rotations
BN = R1(90 * deg)       # B rotated +90° about axis 1 relative to N
RN = R2(-90 * deg)      # R rotated -90° about axis 2 relative to N

# [BR] = [BN] * [NR] = [BN] * [RN]^T
BR = BN @ RN.T

print("BN =\n", BN)
print("\nRN =\n", RN)
print("\nBR =\n", BR)

BN =
 [[ 1.000000e+00  0.000000e+00  0.000000e+00]
 [ 0.000000e+00  6.123234e-17  1.000000e+00]
 [ 0.000000e+00 -1.000000e+00  6.123234e-17]]

RN =
 [[ 6.123234e-17  0.000000e+00  1.000000e+00]
 [ 0.000000e+00  1.000000e+00  0.000000e+00]
 [-1.000000e+00  0.000000e+00  6.123234e-17]]

BR =
 [[ 6.12323400e-17  0.00000000e+00 -1.00000000e+00]
 [ 1.00000000e+00  6.12323400e-17  6.12323400e-17]
 [ 6.12323400e-17 -1.00000000e+00  3.74939946e-33]]


3. Given three reference frames N, B, and F, let the unit base vectors of the coordinate frames B and F be expressed in the N-frame as follows:

$$
\hat{b}_1 = \dfrac{1}{3}
\begin{pmatrix}
1 \\ 2 \\ -2
\end{pmatrix},
\qquad
\hat{b}_2 = \dfrac{1}{\sqrt{2}}
\begin{pmatrix}
0 \\ 1 \\ 1
\end{pmatrix},
\qquad
\hat{b}_3 = \dfrac{1}{3\sqrt{2}}
\begin{pmatrix}
4 \\ -1 \\ 1
\end{pmatrix}
$$

$$
\hat{f}_1 = \dfrac{1}{4}
\begin{pmatrix}
3 \\ -2 \\ \sqrt{3}
\end{pmatrix},
\qquad
\hat{f}_2 = \dfrac{1}{2}
\begin{pmatrix}
-1 \\ 0 \\ \sqrt{3}
\end{pmatrix},
\qquad
\hat{f}_3 = -\dfrac{1}{4}
\begin{pmatrix}
\sqrt{3} \\ 2\sqrt{3} \\ 1
\end{pmatrix}
$$

**Determine the direction cosine matrix [BF]**

In [33]:
import numpy as np

# Define B-frame basis vectors in N-frame
b1 = (1/3) * np.array([1, 2, -2])
b2 = (1/np.sqrt(2)) * np.array([0, 1, 1])
b3 = (1/(3*np.sqrt(2))) * np.array([4, -1, 1])

NB = np.column_stack((b1, b2, b3))   # [NB], columns = b_i in N
print("NB =\n", NB)

# Define F-frame basis vectors in N-frame
f1 = (1/4) * np.array([3, -2, np.sqrt(3)])
f2 = (1/2) * np.array([-1, 0, np.sqrt(3)])
f3 = (-1/4) * np.array([np.sqrt(3), 2*np.sqrt(3), 1])

NF = np.column_stack((f1, f2, f3))
print("\nNF =\n", NF)

# [BF] = [NB]^T * [NF]
BF = NB.T @ NF     
print("\nBF =\n", BF)

# Verify orthogonality
print("\nBF * BF^T =\n", BF @ BF.T)
print("\ndet(BF) =", np.linalg.det(BF))

NB =
 [[ 0.33333333  0.          0.94280904]
 [ 0.66666667  0.70710678 -0.23570226]
 [-0.66666667  0.70710678  0.23570226]]

NF =
 [[ 0.75      -0.5       -0.4330127]
 [-0.5        0.        -0.8660254]
 [ 0.4330127  0.8660254 -0.25     ]]

BF =
 [[-0.37200847 -0.74401694 -0.55502117]
 [-0.04736717  0.61237244 -0.78914913]
 [ 0.92701998 -0.26728038 -0.26304971]]

BF * BF^T =
 [[ 1.00000000e+00  2.40004049e-17  1.62338973e-17]
 [ 2.40004049e-17  1.00000000e+00 -3.79364915e-17]
 [ 1.62338973e-17 -3.79364915e-17  1.00000000e+00]]

det(BF) = 0.9999999999999999


4. Given three reference frames N, B, and F, let the unit base vectors of the coordinate frames B and F be expressed in the N-frame as follows:

$$
\hat{b}_1 = \dfrac{1}{3}
\begin{pmatrix}
1 \\ 2 \\ -2
\end{pmatrix},
\qquad
\hat{b}_2 = \dfrac{1}{\sqrt{2}}
\begin{pmatrix}
0 \\ 1 \\ 1
\end{pmatrix},
\qquad
\hat{b}_3 = \dfrac{1}{3\sqrt{2}}
\begin{pmatrix}
4 \\ -1 \\ 1
\end{pmatrix}
$$

$$
\hat{f}_1 = \dfrac{1}{4}
\begin{pmatrix}
3 \\ -2 \\ \sqrt{3}
\end{pmatrix},
\qquad
\hat{f}_2 = \dfrac{1}{2}
\begin{pmatrix}
-1 \\ 0 \\ \sqrt{3}
\end{pmatrix},
\qquad
\hat{f}_3 = -\dfrac{1}{4}
\begin{pmatrix}
\sqrt{3} \\ 2\sqrt{3} \\ 1
\end{pmatrix}
$$

**Determine the direction cosine matrix [BN]**

In [34]:
BN = NB.T
print("\nBN =\n", BN)



BN =
 [[ 0.33333333  0.66666667 -0.66666667]
 [ 0.          0.70710678  0.70710678]
 [ 0.94280904 -0.23570226  0.23570226]]
