In [1]:
import numpy as np

# Convert from Euler Angles to 3-2-1 DCM
def euler2dcm(theta_1, theta_2, theta_3):
    theta_1 = np.deg2rad(theta_1)
    theta_2 = np.deg2rad(theta_2)
    theta_3 = np.deg2rad(theta_3)

    # 1st axis rotation (Roll)
    C1 = np.array([
        [1, 0,                              0],
        [0, np.cos(theta_3),  np.sin(theta_3)],
        [0, -np.sin(theta_3), np.cos(theta_3)]
    ])

    # 2nd axis rotatio (Pitch)
    C2 = np.array([
        [np.cos(theta_2), 0, -np.sin(theta_2)],
        [0,               1,                0],
        [np.sin(theta_2), 0,  np.cos(theta_2)]
    ])

    # 3rd axis rotation (Yaw)
    C3 = np.array([
        [np.cos(theta_1),  np.sin(theta_1), 0],
        [-np.sin(theta_1), np.cos(theta_1), 0],
        [0,                0,               1]
    ])


    C = C1 @ C2 @ C3
    print(C)

    # Validate C Matrix
    print(np.allclose(C @ C.T, np.eye(3)))
    print(np.linalg.det(C))
    return C


BN = euler2dcm(10, 20, 30)

# 3-1-3 Euler angles extracted FROM THE DCM
Omega = np.arctan2(BN[2,0], -BN[2,1]) 
i     = np.arccos(BN[2,2])
omega = np.arctan2(BN[0,2], BN[1,2])
print(f"{np.rad2deg(Omega)}, {np.rad2deg(i)}, {np.rad2deg(omega)}")

ModuleNotFoundError: No module named 'numpy'

In [ ]:
import numpy as np


def get_321(theta_1, theta_2, theta_3):
    theta_1 = np.deg2rad(theta_1)
    theta_2 = np.deg2rad(theta_2)
    theta_3 = np.deg2rad(theta_3)

    # 1st axis rotation (Roll)
    C1 = np.array([
        [1, 0,                              0],
        [0, np.cos(theta_3),  np.sin(theta_3)],
        [0, -np.sin(theta_3), np.cos(theta_3)]
    ])

    # 2nd axis rotatio (Pitch)
    C2 = np.array([
        [np.cos(theta_2), 0, -np.sin(theta_2)],
        [0,               1,                0],
        [np.sin(theta_2), 0,  np.cos(theta_2)]
    ])

    # 3rd axis rotation (Yaw)
    C3 = np.array([
        [np.cos(theta_1),  np.sin(theta_1), 0],
        [-np.sin(theta_1), np.cos(theta_1), 0],
        [0,                0,               1]
    ])


    C = C1 @ C2 @ C3
    print(C)

    # Validate C Matrix
    print(np.allclose(C @ C.T, np.eye(3)))
    print(np.linalg.det(C))
    return C


BN = get_321(10, 20, 30)
RN = get_321(-5, 5, 5)

# [RB] = [RN][BN]^T
RB = RN @ BN.T


yaw = np.arctan2(RB[1, 0], RB[0, 0])
pitch = np.arcsin(-RB[2, 0])
roll = np.arctan2(RB[2, 1], RB[2, 2])

print(f"{np.rad2deg(yaw)}, {np.rad2deg(pitch)}, {np.rad2deg(roll)}")



[[ 0.92541658  0.16317591 -0.34202014]
 [ 0.01802831  0.88256412  0.46984631]
 [ 0.37852231 -0.44096961  0.81379768]]
True
1.0
[[ 0.99240388 -0.08682409 -0.08715574]
 [ 0.09439131  0.99174183  0.08682409]
 [ 0.07889757 -0.09439131  0.99240388]]
True
1.0
13.22381820632051, 16.368343382025262, 23.617628245331797
