# Quaternion to Direction Cosine Matrix (DCM)

Given the redundant Euler parameters (Euler–Rodrigues quaternion / unit quaternion):

$$
\boldsymbol{\beta} = (\beta_0, \beta_1, \beta_2, \beta_3) = (0.235702,\ 0.471405,\ -0.471405,\ 0.707107)
$$

Determine the corresponding direction cosine matrix $[C]$

In [38]:
import numpy as np

# Given quaternions
q = np.array([0.235702, 0.471405, -0.471405, 0.707107])

# Calculate DCM elements
C11 = q[0] ** 2 + q[1] ** 2 - q[2] ** 2 - q[3] ** 2
C12 = 2 * (q[1] * q[2] - q[0] * q[3])
C13 = 2 * (q[1] * q[3] + q[0] * q[2])
C21 = 2 * (q[1] * q[2] + q[0] * q[3])
C22 = q[0] ** 2 - q[1] ** 2 + q[2] ** 2 - q[3] ** 2
C23 = 2 * (q[2] * q[3] - q[0] * q[1])
C31 = 2 * (q[1] * q[3] - q[0] * q[2])
C32 = 2 * (q[2] * q[3] + q[0] * q[1])
C33 = q[0] ** 2 - q[1] ** 2 - q[2] ** 2 + q[3] ** 2

# DCM 
C = np.array([ [C11, C12, C13],
               [C21, C22, C23],
               [C31, C32, C33] ])
# Results
print(f"[C]={C}")
print(f"Verification: C x C^T = I:\n {np.round(C @ C.T, decimals = 4)}")

[C]=[[-0.44444488 -0.77777842  0.44444535]
 [-0.11111228 -0.44444488 -0.88888975]
 [ 0.88888975 -0.44444535  0.11111039]]
Verification: C x C^T = I:
 [[ 1.  0. -0.]
 [ 0.  1. -0.]
 [-0. -0.  1.]]


In [39]:
import numpy as np

# DCM 
C = np.array([ [-0.529403, -0.467056,  0.708231],
               [-0.474115, -0.529403, -0.703525],
               [0.703525,  -0.708231, 0.0588291]
            ])

# Sheppard's Method for extracting quaternions from DCM
# Compute q0^2, q1^2, q2^2, q3^2 and select the largest
q2 = np.array([ 0.25 * (1 + np.trace(C)), 
                0.25 * (1 + 2 * C[0][0] - np.trace(C)), 
                0.25 * (1 + 2 * C[1][1] - np.trace(C)), 
                0.25 * (1 + 2 * C[2][2] - np.trace(C))
             ])

max_q2_idx = np.argmax(q2) # Index for the largest qi^2 value

# Compute Sheppard's method for qi 
match max_q2_idx:
    case 0:
        q0 = np.sqrt(q2[max_q2_idx])
        q1 = 0.25 * (C[1][2] - C[2][1]) / q0
        q2 = 0.25 * (C[2][0] - C[0][2]) / q0
        q3 = 0.25 * (C[0][1] - C[1][0]) / q0
    
    case 1:
        q1 = np.sqrt(q2[max_q2_idx])
        q0 = 0.25 * (C[1][2] - C[2][1]) / q1
        q2 = 0.25 * (C[0][1] + C[1][0]) / q1
        q3 = 0.25 * (C[0][2] + C[2][0]) / q1

    case 2:
        q2 = np.sqrt(q2[max_q2_idx])
        q0 = 0.25 * (C[2][0] - C[0][2]) / q2
        q1 = 0.25 * (C[0][1] + C[1][0]) / q2
        q3 = 0.25 * (C[1][2] + C[2][1]) / q2
    
    case 3:
        q3 = np.sqrt(q2[max_q2_idx])
        q0 = 0.25 * (C[0][1] - C[1][0]) / q3
        q1 = 0.25 * (C[0][2] + C[2][0]) / q3
        q2 = 0.25 * (C[1][2] + C[2][1]) / q3

# Results 
q = np.array([q0, q1, q2, q3])

print(f"q = {q}")      
print (f"Verification: q0^2 + q1^2 + q2^2 + q3^3 = 1 = {q0 ** 2 + q1 ** 2 + q2 ** 2 + q3 ** 2}")


q = [ 0.00242542  0.48506963 -0.48506963  0.72760482]
Verification: q0^2 + q1^2 + q2^2 + q3^3 = 1 = 0.9999997465692992


In [ ]:
import numpy as np

theta_1 = np.deg2rad(20)
theta_2 = np.deg2rad(10)
theta_3 = np.deg2rad(-10)

# 1st axis rotation (Roll)
C1 = np.array([
    [1, 0,                              0],
    [0, np.cos(theta_3),  np.sin(theta_3)],
    [0, -np.sin(theta_3), np.cos(theta_3)]
])

# 2nd axis rotation (Pitch)
C2 = np.array([
    [np.cos(theta_2), 0, -np.sin(theta_2)],
    [0,               1,                0],
    [np.sin(theta_2), 0,  np.cos(theta_2)]
])

# 3rd axis rotation (Yaw)
C3 = np.array([
    [np.cos(theta_1),  np.sin(theta_1), 0],
    [-np.sin(theta_1), np.cos(theta_1), 0],
    [0,                0,               1]
])


C = C1 @ C2 @ C3
print(f"Verification: {C @ C.T}")

# Sheppard's Method for extracting quaternions from DCM
# Compute q0^2, q1^2, q2^2, q3^2 and select the largest
q2 = np.array([ 0.25 * (1 + np.trace(C)), 
                0.25 * (1 + 2 * C[0][0] - np.trace(C)), 
                0.25 * (1 + 2 * C[1][1] - np.trace(C)), 
                0.25 * (1 + 2 * C[2][2] - np.trace(C))
             ])

max_q2_idx = np.argmax(q2) # Index for the largest qi^2 value

# Compute Sheppard's method for qi 
match max_q2_idx:
    case 0:
        q0 = np.sqrt(q2[max_q2_idx])
        q1 = 0.25 * (C[1][2] - C[2][1]) / q0
        q2 = 0.25 * (C[2][0] - C[0][2]) / q0
        q3 = 0.25 * (C[0][1] - C[1][0]) / q0
    
    case 1:
        q1 = np.sqrt(q2[max_q2_idx])
        q0 = 0.25 * (C[1][2] - C[2][1]) / q1
        q2 = 0.25 * (C[0][1] + C[1][0]) / q1
        q3 = 0.25 * (C[0][2] + C[2][0]) / q1

    case 2:
        q2 = np.sqrt(q2[max_q2_idx])
        q0 = 0.25 * (C[2][0] - C[0][2]) / q2
        q1 = 0.25 * (C[0][1] + C[1][0]) / q2
        q3 = 0.25 * (C[1][2] + C[2][1]) / q2
    
    case 3:
        q3 = np.sqrt(q2[max_q2_idx])
        q0 = 0.25 * (C[0][1] - C[1][0]) / q3
        q1 = 0.25 * (C[0][2] + C[2][0]) / q3
        q2 = 0.25 * (C[1][2] + C[2][1]) / q3

# Results 
q = np.array([q0, q1, q2, q3])

print(f"q = {q}")      
print (f"Verification: q0^2 + q1^2 + q2^2 + q3^3 = 1 = {q0 ** 2 + q1 ** 2 + q2 ** 2 + q3 ** 2}")




Verification: [[ 1.00000000e+00 -1.42033036e-18  6.46798779e-17]
 [-1.42033036e-18  1.00000000e+00 -1.85529329e-17]
 [ 6.46798779e-17 -1.85529329e-17  1.00000000e+00]]
3
q = [-0.43273162  0.3762158  -0.08025683  0.81533052]
Verification: q0^2 + q1^2 + q2^2 + q3^3 = 1 = 0.9999999999999999
