# Euler Parameter Addition

Given the following unit quaternions:

- $\beta_{B/N} = (0.774597, 0.258199, 0.516398, 0.258199)$  
  (attitude of B relative to N)

- $\beta_{F/B} = (0.359211, 0.898027, 0.179605, 0.179605)$  
  (attitude of F relative to B)

Find the Euler parameter set $\beta_{F/N}$ that corresponds to the short rotation.

In [24]:
import numpy as np
# Problem's  input
beta_d = np.array([0.774597, 0.258199, 0.516398, 0.258199]) # First rotation
beta_dd = np.array([0.359211, 0.898027, 0.179605, 0.179605]) # Second rotation

b0, b1, b2, b3 = beta_dd
c0, c1, c2, c3 = beta_d

# [B''] Matrix
B_dd = np.array([[b0, -b1, -b2, -b3],
                 [b1, b0, b3, -b2],
                 [b2, -b3, b0, b1],
                 [b3, b2, -b1, b0]])
# [B'] Matrix
B_d = np.array([[c0], [c1], [c2], [c3]])

# Final orientation [B] = [B'']x[B']
Beta = B_dd @ B_d

if Beta[0,0] < 0:
    Beta = -Beta # Transform to shortest rotation

# Results
print(f"[B]=\n{Beta}")
print(f"\nVerification: [B'']x[B'']^T =\n{B_dd@B_dd.T}")

[B]=
[[ 0.0927474 ]
 [-0.83473077]
 [-0.51011318]
 [ 0.1854961 ]]

Verification: [B'']x[B'']^T =
[[ 1.00000095e+00 -2.49515272e-17  7.24596720e-18  5.78634003e-19]
 [-2.49515272e-17  1.00000095e+00  7.24596720e-18  1.44564218e-17]
 [ 7.24596720e-18  7.24596720e-18  1.00000095e+00 -2.89375816e-17]
 [ 5.78634003e-19  1.44564218e-17 -2.89375816e-17  1.00000095e+00]]


# Euler Parameter Addition

Given the following unit quaternions:

- $\beta_{F/N} = (0.359211, 0.898027, 0.179605, 0.179605)$  
  (attitude of F relative to N)
- $\beta_{B/N} = (-0.377964, 0.755929, 0.377964, 0.377964)$  
  (attitude of B relative to N)



Find the Euler parameter set $\beta_{F/B}$ that corresponds to the short rotation.

In [25]:
import numpy as np

Beta = np.array([[0.359211],[0.898027], [0.179605], [0.179605]]) # Final orientation
beta_d = np.array([-0.377964, 0.755929, 0.377964, 0.377964]) # First rotation

c0, c1, c2, c3 = beta_d

# [B'] Matrix
Beta_d = np.array([[c0, -c1, -c2, -c3],
                   [c1, c0, -c3, c2],
                   [c2, c3, c0, -c1],
                   [c3, -c2, c1, c0]])
# [B''] = [B']^T @ [B]
Beta_dd = Beta_d.T @ Beta

if Beta_dd[0,0] < 0:
    Beta_dd = -Beta_dd # Transform to shortest rotation

# Results
print(f"[B'']=\n{np.round(Beta_dd, decimals=6)}")
print(f"Verification: [B']x[B']^T =\n{Beta_d@Beta_d.T}")

[B'']=
[[ 0.678844]
 [-0.61096 ]
 [-0.407306]
 [ 0.      ]]
Verification: [B']x[B']^T =
[[ 9.99999009e-01 -2.83331077e-17  3.87756596e-17  5.77532063e-19]
 [-2.83331077e-17  9.99999009e-01  1.67354916e-17  5.49336192e-17]
 [ 3.87756596e-17  1.67354916e-17  9.99999009e-01 -1.67354916e-17]
 [ 5.77532063e-19  5.49336192e-17 -1.67354916e-17  9.99999009e-01]]
