In [53]:
import numpy as np

beta_d = np.array([0.774597, 0.258199, 0.516398, 0.258199])
beta_dd = np.array([0.359211, 0.898027, 0.179605, 0.179605])

b0, b1, b2, b3 = beta_dd
c0, c1, c2, c3 = beta_d


B_dd = np.array([[b0, -b1, -b2, -b3],
                 [b1, b0, b3, -b2],
                 [b2, -b3, b0, b1],
                 [b3, b2, -b1, b0]])

B_d = np.array([[c0], [c1], [c2], [c3]])

Beta = B_dd @ B_d

if Beta[0,0] < 0:
    Beta = -Beta
print(Beta)

#print(B_dd@B_dd.T)

[[ 0.0927474 ]
 [-0.83473077]
 [-0.51011318]
 [ 0.1854961 ]]


In [47]:
import numpy as np

Beta = np.array([[0.359211],[0.898027], [0.179605], [0.179605]])
beta_d = np.array([-0.377964, 0.755929, 0.377964, 0.377964])

c0, c1, c2, c3 = beta_d

Beta_d = np.array([[c0, -c1, -c2, -c3],
                   [c1, c0, -c3, c2],
                   [c2, c3, c0, -c1],
                   [c3, -c2, c1, c0]])

Beta_dd = Beta_d.T @ Beta

print(np.round(Beta_dd, decimals=6))
print(Beta_d@Beta_d.T)






[[ 0.678844]
 [-0.61096 ]
 [-0.407306]
 [ 0.      ]]
[[ 9.99999009e-01  0.00000000e+00 -5.55111512e-17  0.00000000e+00]
 [ 0.00000000e+00  9.99999009e-01  0.00000000e+00  2.77555756e-17]
 [-5.55111512e-17  0.00000000e+00  9.99999009e-01  0.00000000e+00]
 [ 0.00000000e+00  2.77555756e-17  0.00000000e+00  9.99999009e-01]]
